version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '3000:80'
    restart: unless-stopped

  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./:/app:cached
      - /app/node_modules
    ports:
      - '3002:5173'
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npx quasar dev -p 5173 --hostname 0.0.0.0"
    tty: true
    stdin_open: true
